### ISSUE TITLE
Possible compat issue with Woods and Mires

### ISSUE THREAD

**Issue by Sunconure11** [cScotPlay/Rusticated#13]
https://pastebin.com/x4uHbkun

**Comment by Juuxel** [comment]
The code in `VegetationGeneration` breaks since WaM's pine forests are in both `is_taiga` and `is_forest`, so it adds the same feature twice. This should be fixable by OR'ing the two conditions together.

https://github.com/cScotPlay/Rusticated/blob/33b0c806b93af964653c79985af3d602cff97e82/src/main/java/net/mcs3/rusticated/world/level/levelgen/generation/VegetationGeneration.java#L28-L29

Additionally, it'd be very good if Rusticated specified a custom namespace like its mod ID when it registers its configured features; currently, they show up as `minecraft` features which can lead to collisions and is not helpful when debugging.

**Comment by Sunconure11** [comment]
@cScotPlay

**Comment by Sunconure11** [comment]
I think this issue should be resurrected, so that this can be fixed while issues with Woods and Mires are being stomped out @cScotPlay

**Comment by cScotPlay** [comment]
Issue fixed in version 2.0.6
